### ISSUE TITLE
After the transformation, the js imports remain "as is" and without extensions

### ISSUE THREAD

**Issue by PurpleTape** [ManBearTM/vite-plugin-no-bundle#11]
Hello!

It's great that there is such a Vite plugin that allows you to skip the bundling step.

I am trying to use a plugin to build my backend application and have encountered the following difficulties: when transforming files, imports from `node_modules` remain "as is"

For example, in a transformed file, I'm trying to import a file from `node_modules`:
```ts
import { Module } from '@nestjs/common';
```
Then JS will understand this and the `node_modules/@nestjs/common/index.js` file will be imported.

But when I try to import a specific file:
```ts
import { ROUTE_ARGS_METADATA } from '@nestjs/common/constants';
```
Then when I launch the application, I encounter an error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...' imported from ...
Did you mean to import @nestjs/common/constants.js?
```
That is, Node JS cannot import the file because it is missing `.js` in the file path.

At the same time, the plugin transforms the application files correctly, adding extensions when importing local files.

There is no such problem in Vite itself, since in development mode Vite processes imports correctly, and in build mode Vite combines all the code in single file.

Please clarify if I am using the plugin correctly and is there a way to fix this problem?

Thanks!

**Comment by ManBearTM** [comment]
Hi!

I understand your problem. I believe you are using the plugin correctly and are doing things the correct way. I think this is ultimately a "problem" with the `@nestjs/common` package. If they want developers to be able to import the constants file, they need to add an `exports` section to their `package.json`. Something like this:

```json
"exports": {
  ".": {
    "types": "./index.d.ts",
    "default": "./index.js"
  },
  "./constants": {
    "types": "./constants.d.ts",
    "default": "./constants.js"
  }
}
```

I would probably start with opening a PR in their repo with that. 

Regarding this plugin, I could certainly add the extension when I'm resolving the externals, but I'm afraid of breaking all sorts of cases for other users by rewriting the `import` statements. As a workaround, the easiest is to just add a `.js` extension to the `@nestjs/common/constants` statement. It may not look as pretty, but it should do no harm. If you are really against that, you could also consider using the `internal` configuration of this plugin to include the constants in your build output:

```js
noBundle({
  internal: '@nestjs/common/constants',
})
```

Hope that helps!
