### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by jcbhmr** [ManBearTM/vite-plugin-no-bundle#4]
Hello! 👋

I'd love to see the readme be improved! Particularly with the example use cases. Maybe even linking to a project that uses this plugin in the wild so that a prospective user can see it in action in a real-world scenario.

Something like this maybe? (except tailored to this project) https://gist.github.com/jcbhmr/77de296e4e7b3c42855ea927c7409e53 or https://gist.github.com/jcbhmr/5fa35ec1c7208018e9dce2a9e06af0cf

I am willing to contribute code to do this, I just don't want to be in PR limbo forever. ❤

**Comment by ManBearTM** [comment]
Hi!

Sure, there’s always room for improvement 🙂 

One thing I would love to have is an `examples` directory that shows different use cases (would be helpful for development as well). I don’t know if there are any relevant projects out there that we could link to, but good suggestion. 

I will definitely help if you contribute with a PR, but with a newborn in the house, I can’t dedicate a lot of time for development myself. But I’ll make sure it doesn’t end up in “PR limbo” 😄
