### ISSUE TITLE
fileNames can not be a function as the readme indicates.

### ISSUE THREAD

**Issue by morganney** [ManBearTM/vite-plugin-no-bundle#6]
Not sure if this is an oversight and this packages does want to support `fileNames` as a function, but the README and code appear to be out of sync. Right now `fileNames` only supports a `string` value.

**Comment by ManBearTM** [comment]
Thanks for the report! You are right, the types appear to be incorrect. It should indeed support a function as well. I'll get it fixed! In the meantime, you should be able to work around this, since it is only a type issue. If you cast your fileNames function as `any` it should work.

**Comment by morganney** [comment]
Perfect, thanks. Then perhaps I will not need to use something like [`vite-plugin-specifier`](https://www.npmjs.com/package/vite-plugin-specifier)  to create a dual build with this plugin.

**Comment by ManBearTM** [comment]
@morganney I have added support for multiple formats in #7. It is published as a beta version if you wish to test it:

```sh
npm install vite-plugin-no-bundle@3.0.0-beta.1
```

Do you think this solves your problem?

**Comment by ManBearTM** [comment]
Original issue regarding incorrect types fixed in minor version 2.0.3.

**Comment by morganney** [comment]
@ManBearTM the changes in #7 will support the use case I [mentioned](https://github.com/ManBearTM/vite-plugin-no-bundle/issues/2#issuecomment-1666854005), thanks.
