### ISSUE TITLE
Is it possible to stop it from bundling node_modules?

### ISSUE THREAD

**Issue by RIP21** [ManBearTM/vite-plugin-no-bundle#8]
Now it extracts away files from `node_modules` and while it's not bundling them, it kinda is, by putting them into `dist` folder.
If that wouldn't break things I wouldn't care, but it does :)
To be clear, I set `dependencies`  and `peerDependencies` from `./package.json` as external. These are, likely, transitive dependencies coming from dependencies.

Here is a screenshot that shows that:
![CleanShot 2024-03-10 at 15 59 38@2x](https://github.com/ManBearTM/vite-plugin-no-bundle/assets/3940079/a013ba40-7cd4-4e65-abbd-0f121185d895)

**Comment by RIP21** [comment]
Solution:
```
      rollupOptions: {
        plugins: [
          peerDepsExternal({
            includeDependencies: true,
          }),
        ],
      },

```
use `includeDependencies: true,` from   `import peerDepsExternal from 'rollup-plugin-peer-deps-external'`. And you will be good. I tried to be smart and use just package json keys, but it's not enough for PNPM :)

**Comment by ManBearTM** [comment]
I'm glad you found a solution, but I wonder why you need to use that other plugin. This plugin should already externalize node modules ([code here](https://github.com/ManBearTM/vite-plugin-no-bundle/blob/96e140fd14258048febcdd8dbc6a9c49c894a25a/src/index.ts#L8), so perhaps there is an edge case I'm not handling correctly? Comparing "rollup-plugin-peer-deps-external" to this plugin, I can see that I take a simpler approach by assuming things about the import path, while the rollup plugin seems to actually parse the package.json file for dependency names 🤔

Feel free to share some more information about your setup if you like, then I'd be happy to look into it.

**Comment by RIP21** [comment]
Oh, I applied your plugin on top of the existing vite config that was already using peer deps plugin, so I just kept it. So maybe it wasn't even needed. I'll try to remove it completely and see a result now. Thanks for the heads up!

**Comment by RIP21** [comment]
@ManBearTM I removed peer deps plugin plugin and, at least for PNPM, I'm not sure how it will behave for `npm` and `yarn`, it broke and returned back to the initial problem. So, at least for PNPM, this is needed as it probably externalizes it somehow in a better way.

**Comment by ManBearTM** [comment]
I found some issues with `node_modules` when using Vite 5, so I made some changes and updated the plugin to require Vite 5 (from v4). If you want to check it out I just released v4 of this plugin. Hopefully it should no longer require the additional `peerDepsExternal` plugin in order to externalize `node_modules.`

**Comment by RIP21** [comment]
@ManBearTM i'll test and report back. Thanks
